services:
  - type: web
    name: backend-api
    runtime: node
    rootDir: backend

    buildCommand: npm install
    startCommand: node server.js

    envVars:
      - key: NODE_VERSION
        value: 22

  - type: web
    name: frontend-web
    runtime: static
    rootDir: frontend

    buildCommand: npm install && npm run build
    staticPublishPath: dist

    envVars:
      - key: VITE_API_URL
        value: https://backend-api.onrender.com