services:
  - type: web
    name: backend-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

    envVars:
      - key: NODE_VERSION
        value: 22

  - type: static
    name: frontend-web
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

    envVars:
      - key: VITE_API_URL
        value: https://backend-api.onrender.com